version: '3'
services:
  frontend:
    image: gonzalo91/tareas-frontend:latest
    ports:
      - "4042:80"

  backend:
    image: gonzalo91/tareas-backend:latest
    ports:
      - "4043:4043"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tareas

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
